### ISSUE TITLE
http://app.highlight.io/logs not loading

### ISSUE THREAD

**Issue by abh** [highlight/highlight#7346]
In latest Safari (with common adblockers enabled?) http://app.highlight.io/logs? doesn't load.

I get that adblocking makes this harder (the blocked file was something from hubspot), but I'd expect a "fullstack monitoring platform" to be able to have its own website load despite hubspot tracking being blocked (or otherwise unavailable!)

<img width="755" alt="Screenshot 2023-12-16 at 10 01 28" src="https://github.com/highlight/highlight/assets/16861/b76f341b-f298-4305-9d55-b0bdfbc13370">

**Comment by abh** [comment]
oh, different set of blocked content and failures this time:

<img width="937" alt="Screenshot 2023-12-16 at 10 07 25" src="https://github.com/highlight/highlight/assets/16861/7531f4d8-4bb7-48c7-afef-d42bd45a1c16">

**Comment by Vadman97** [comment]
Hey @abh 
Found your sessions - taking a look. Looks like there was a potential issue with our indexeddb caching.
https://app.highlight.io/1/sessions/FvZCh4ZdwoBLvqI3ICY1UtGu9qbg
https://app.highlight.io/1/sessions/P7MH1JEJ6wSwODl1dOJFDIvGW4lH
https://app.highlight.io/1/sessions/1Fl2Zcfndw15KlbBNQ3v5ybx1UDK

**Comment by Vadman97** [comment]
Hi @abh , this should be fixed as we have [invalidated](https://github.com/highlight/highlight/blob/240a0d40cfe0d57b773c000f2528c854aef5cd0c/frontend/src/util/db.ts#L85) our frontend cache version. Going forward, we are working on some updates to our indexeddb caching to prevent such issues.

**Comment by abh** [comment]
I randomly came across this issue and figured I should try it again and it still isn't working. Different problem this time though.

<img width="915" alt="Screenshot 2024-10-23 at 09 23 21" src="https://github.com/user-attachments/assets/e7b9ee24-f8c9-4acf-a6e2-7b2ea0dfad86">
